services:
  - type: web
    name: breathe-esg-backend
    runtime: python
    pythonVersion: 3.10
    workingDir: backend
    
    buildCommand: pip install -r requirements.txt && python manage.py migrate
    startCommand: gunicorn config.wsgi:application
    
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://breathe-esg-frontend.vercel.app"

databases:
  - name: postgres
    databaseName: breathe_esg
    user: breathe_esg_user
