# Generated by Django 4.2.11 on 2026-05-27 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SAP', 'SAP Fuel & Procurement'), ('UTILITY', 'Utility Electricity Data'), ('TRAVEL', 'Corporate Travel')], max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('raw_file_name', models.CharField(max_length=255)),
                ('raw_file_size', models.IntegerField()),
                ('total_rows', models.IntegerField(default=0)),
                ('successful_rows', models.IntegerField(default=0)),
                ('failed_rows', models.IntegerField(default=0)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('SCOPE_1', 'Scope 1 - Direct'), ('SCOPE_2', 'Scope 2 - Indirect (Energy)'), ('SCOPE_3', 'Scope 3 - Indirect (Other)')], max_length=20)),
                ('category', models.CharField(choices=[('FUEL_DIESEL', 'Fuel - Diesel'), ('FUEL_PETROL', 'Fuel - Petrol'), ('FUEL_LPG', 'Fuel - LPG'), ('FUEL_CNG', 'Fuel - CNG'), ('ELECTRICITY', 'Electricity'), ('TRAVEL_FLIGHT', 'Travel - Flight'), ('TRAVEL_HOTEL', 'Travel - Hotel'), ('TRAVEL_GROUND', 'Travel - Ground Transport')], max_length=50)),
                ('activity_date', models.DateField(help_text='When did this activity occur?')),
                ('normalized_value', models.DecimalField(decimal_places=4, max_digits=15)),
                ('normalized_unit', models.CharField(help_text='kWh, kg, km, etc.', max_length=20)),
                ('original_unit', models.CharField(blank=True, max_length=20, null=True)),
                ('emission_factor', models.DecimalField(decimal_places=6, help_text='kg CO2e per unit', max_digits=10)),
                ('calculated_emissions', models.DecimalField(decimal_places=4, help_text='kg CO2e', max_digits=15)),
                ('confidence_score', models.FloatField(default=1.0, help_text='0.0-1.0. How confident are we in this data?')),
                ('suspicious_flags', models.JSONField(blank=True, default=dict, help_text='Why was this flagged?')),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending Review'), ('FLAGGED', 'Flagged - Suspicious'), ('APPROVED', 'Approved for Audit'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='emissions.datasource')),
            ],
            options={
                'ordering': ['-activity_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Record Created'), ('FLAGGED', 'Flagged Suspicious'), ('UNFLAGGED', 'Unflagged'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EDITED', 'Edited')], max_length=20)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('emission_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_history', to='emissions.emissionrecord')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_json', models.JSONField()),
                ('processing_status', models.CharField(choices=[('PENDING', 'Pending Normalization'), ('NORMALIZED', 'Successfully Normalized'), ('FAILED', 'Normalization Failed'), ('APPROVED', 'Approved for Audit'), ('REJECTED', 'Rejected by Analyst')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='emissions.datasource')),
            ],
            options={
                'ordering': ['data_source', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='emissions.organization'),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='raw_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emission_record', to='emissions.rawrecord'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissions.organization'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='rawrecord',
            index=models.Index(fields=['data_source', 'processing_status'], name='emissions_r_data_so_260ad4_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['organization', 'scope', 'review_status'], name='emissions_e_organiz_cbe9aa_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['organization', 'activity_date'], name='emissions_e_organiz_143c84_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['review_status'], name='emissions_e_review__5517f6_idx'),
        ),
    ]
