# Generated by Django 4.2.11 on 2026-05-27 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_approved_at', models.DateTimeField(blank=True, null=True)),
                ('second_approved_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('emission_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval_chain', to='emissions.emissionrecord')),
                ('first_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_approvals', to=settings.AUTH_USER_MODEL)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_locks', to=settings.AUTH_USER_MODEL)),
                ('second_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Approval Chain',
                'verbose_name_plural': 'Approval Chains',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('UPLOAD', 'File Uploaded'), ('PROCESS', 'File Processed'), ('APPROVE', 'Record Approved'), ('REJECT', 'Record Rejected'), ('FLAG', 'Record Flagged'), ('EDIT', 'Record Edited'), ('DELETE', 'Record Deleted'), ('EXPORT', 'Data Exported')], max_length=20)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('changes', models.JSONField(default=dict)),
                ('reason', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('emission_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emissions.emissionrecord')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissions.organization')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-performed_at'],
                'indexes': [models.Index(fields=['organization', 'action'], name='audits_audi_organiz_9df41c_idx'), models.Index(fields=['performed_at'], name='audits_audi_perform_b5c80e_idx')],
            },
        ),
    ]
